### PR TITLE
php: many changes to satisfy linter

### PR DESCRIPTION
**Pull request by vanyauhalin**
I corrected errors, but there was one function ([`getResponseUri`](https://github.com/ONLYOFFICE/document-server-integration/blob/94619521a869733ff64263039753ab9e3ebb3083/web/documentserver-example/php/src/functions.php#L772)) that I didn't touch. I don't understand its signature and why the function itself is needed since it isn't used anywhere.

### CODE REVIEW

**Comment by rivexe** [comment]
First of all, I didn't understand [this](https://github.com/ONLYOFFICE/document-server-integration/pull/444/commits/94619521a869733ff64263039753ab9e3ebb3083#diff-931bfdfcfdadfc9685f2d544c3d0f533098b1b58e0f9fb070d747869971de4aaR29).

What's wrong with [this ](https://github.com/ONLYOFFICE/document-server-integration/pull/444/commits/6518cabf612186733e8b8fd9acf0f936231a9556#diff-839b5e2067468733913e390043a0c10672117ab2d4f210d251fe0f1fddd76025R1)rule?

**Comment by vanyauhalin** [comment]
> First of all, I didn't understand [this](https://github.com/ONLYOFFICE/document-server-integration/pull/444/commits/94619521a869733ff64263039753ab9e3ebb3083#diff-931bfdfcfdadfc9685f2d544c3d0f533098b1b58e0f9fb070d747869971de4aaR29).

Here, I've set more specific paths for the linter to the source files. In previous implementations, I used a dot (`.`) which meant to lint all PHP files in the current directory, including the `vendor` directory which contains code not controlled by us. However, now that I've moved all the source code to the `src` directory, I can set more specific paths. I've made the same change in the [Makefile](https://github.com/ONLYOFFICE/document-server-integration/blob/refactor/php-linting/web/documentserver-example/php/Makefile#L66) as well.

> What's wrong with [this ](https://github.com/ONLYOFFICE/document-server-integration/pull/444/commits/6518cabf612186733e8b8fd9acf0f936231a9556#diff-839b5e2067468733913e390043a0c10672117ab2d4f210d251fe0f1fddd76025R1)rule?

Here, I've disabled this rule because it seems like a false positive for us.

```text
 1 | WARNING | A file should declare new symbols (classes, functions,
   |         | constants, etc.) and cause no other side effects, or it should
   |         | execute logic with side effects, but should not do both. The
   |         | first symbol is defined on line 31 and the first side effect is
   |         | on line 20.
```

**Comment by rivexe** [comment]
> > First of all, I didn't understand [this](https://github.com/ONLYOFFICE/document-server-integration/pull/444/commits/94619521a869733ff64263039753ab9e3ebb3083#diff-931bfdfcfdadfc9685f2d544c3d0f533098b1b58e0f9fb070d747869971de4aaR29).
> 
> Here, I've set more specific paths for the linter to the source files. In previous implementations, I used a dot (`.`) which meant to lint all PHP files in the current directory, including the `vendor` directory which contains code not controlled by us. However, now that I've moved all the source code to the `src` directory, I can set more specific paths. I've made the same change in the [Makefile](https://github.com/ONLYOFFICE/document-server-integration/blob/refactor/php-linting/web/documentserver-example/php/Makefile#L66) as well.
> 
> > What's wrong with [this ](https://github.com/ONLYOFFICE/document-server-integration/pull/444/commits/6518cabf612186733e8b8fd9acf0f936231a9556#diff-839b5e2067468733913e390043a0c10672117ab2d4f210d251fe0f1fddd76025R1)rule?
> 
> Here, I've disabled this rule because it seems like a false positive for us.
> 
> ```
>  1 | WARNING | A file should declare new symbols (classes, functions,
>    |         | constants, etc.) and cause no other side effects, or it should
>    |         | execute logic with side effects, but should not do both. The
>    |         | first symbol is defined on line 31 and the first side effect is
>    |         | on line 20.
> ```

1. Got it.
2. Why do you think so? We used to follow this rule, if I remember correctly.

**Comment by vanyauhalin** [comment]
> 2. Why do you think so? We used to follow this rule, if I remember correctly.

Sorry for such a long reply.

This warning is a false positive, because `index.php` serves as the starting point of the program. In this file, there're side effects caused by the `require_once` statement, and two functions are declared. These functions are used to separate the server configuration into two steps: the configuration itself and the router's configuration. 

I don't see any reason why we should move these functions to another file and then require them in `index.php`. Similarly, there is no need to delete the functions and write a plain script, as there're no errors being thrown.

It's easier for me to turn off the rule for this file instead of breaking the structured code.

**Review by rivexe — APPROVED** [review]

**Pull request merged**
