### PR TITLE
ruby: add support for formats

### PR DESCRIPTION
**Pull request by vanyauhalin**

### CODE REVIEW

**Review by rivexe — APPROVED** [review]

**Comment by aleksandrfedorov97** [comment]
These variables should also be changed to use the format matrix:
https://github.com/ONLYOFFICE/document-server-integration/blob/feature/ruby-matrix-formats/web/documentserver-example/ruby/app/models/file_utility.rb#L20-L27

**Comment by vanyauhalin** [comment]
> These variables should also be changed to use the format matrix:
> https://github.com/ONLYOFFICE/document-server-integration/blob/feature/ruby-matrix-formats/web/documentserver-example/ruby/app/models/file_utility.rb#L20-L27

Did this.

**Comment by vanyauhalin** [comment]
@aleksandrfedorov97, please take a look at the new changes. I've added memorization for the high-cost method in the `FormatManager`.

**Review by aleksandrfedorov97 — APPROVED** [review]

**Comment by vanyauhalin** [comment]
@LinneyS, is ready to merge.

**Pull request merged**
